ALTER TABLE lectures
    MODIFY COLUMN semester VARCHAR(20) NOT NULL,
    MODIFY COLUMN lecture_type VARCHAR(20) NOT NULL,
    MODIFY COLUMN college VARCHAR(60) NOT NULL,
    MODIFY COLUMN department VARCHAR(60) NOT NULL,
    MODIFY COLUMN target VARCHAR(40) NOT NULL,
    MODIFY COLUMN course_number VARCHAR(40) NOT NULL,
    MODIFY COLUMN lecture_number VARCHAR(40) NOT NULL,
    MODIFY COLUMN title VARCHAR(100) NOT NULL,
    MODIFY COLUMN subtitle VARCHAR(100) NOT NULL,
    MODIFY COLUMN lecturer VARCHAR(100) NOT NULL;